"""P0 worker: run ONE scenario against the real Leash production server,
using the deterministic decision_engine.evaluate_purchase() classifier.

Usage:
    cd backend && source .venv/bin/activate
    python3 leash_worker.py SCEN0000

Requires LEASH_BASE_URL and TEAM_API_KEY in the environment (e.g. via a
gitignored backend/.env, loaded below with python-dotenv). Never prints
either value.
"""
from __future__ import annotations

import sys
import time
from datetime import datetime, timezone

from dotenv import load_dotenv

load_dotenv()

from leash_adapter import authorization_event_to_purchase, engine_decision_to_leash_decision, mandate_snapshot_to_engine_policy
from leash_client import LeashApiError, LeashClient
from leash_ledger import LeashLedger
from decision_engine import evaluate_purchase

LEDGER_PATH = "logs/leash_interactions.jsonl"


def _parse_iso(ts: str) -> datetime:
    return datetime.fromisoformat(ts.replace("Z", "+00:00"))

# Default: a generous, hand-authored mandate - NOT generated by the local
# LLM parser (that produces our own flat Schema, not the real Viseca
# hard_rules shape). Callers may pass a different instruction/hard_rules to
# deliberately exercise decline/step_up paths; this is a testing choice made
# by the caller, never a scenario_id-keyed branch inside engine or client
# code.
DEFAULT_MANDATE_INSTRUCTION = "Allow grocery purchases up to CHF 1000 per item."
DEFAULT_MANDATE_HARD_RULES = [
    {"field": "authorization.items.item_category", "operator": "in", "value": ["groceries"], "scope": "purchase"},
    {"field": "authorization.billing_amount_chf", "operator": "<=", "value": 1000, "currency": "CHF", "scope": "purchase"}
]

# Process-lifetime only, per P0 scope - no durable store yet (same
# no-persistence limitation already true of the local demo flow).
_already_decided: set[str] = set()
_redeliveries: list[str] = []


def run_scenario(scenario_id: str, instruction: str | None = None, hard_rules: list[dict] | None = None) -> dict:
    instruction = instruction or DEFAULT_MANDATE_INSTRUCTION
    hard_rules = hard_rules if hard_rules is not None else DEFAULT_MANDATE_HARD_RULES

    ledger = LeashLedger(LEDGER_PATH)
    client = LeashClient(ledger=ledger)
    client.scenario_id = scenario_id

    print("== /healthz ==")
    print(client.healthz())

    print("== /v1/bootstrap ==")
    boot = client.bootstrap()
    decision_timeout = boot["timeouts"]["decision_timeout_seconds"]
    poll_wait = int(boot["timeouts"]["long_poll_max_wait_seconds"])
    print(f"decision_timeout_seconds={decision_timeout} long_poll_max_wait_seconds={poll_wait} pack_version={boot.get('pack_version')}")

    print("== create + confirm mandate ==")
    draft = client.create_mandate(instruction, hard_rules)
    draft_id = draft["draft_id"]
    confirmed = client.confirm_mandate(draft_id)
    mandate_id = confirmed["mandate_id"]
    print(f"mandate_id={mandate_id} status={confirmed['status']}")

    print(f"== create scenario run for {scenario_id} ==")
    run = client.create_scenario_run(mandate_id, scenario_id)
    run_id = run["run_id"]
    client.run_id = run_id
    print(f"run_id={run_id} status={run['status']} counters={run['counters']}")

    decided = []
    while True:
        current_run = client.get_scenario_run(run_id)
        # counters.remaining means "not yet generated/queued" - it can be 0
        # while an event is still pending decision. status == "completed" is
        # the one authoritative exit signal (proven via the ledger: the
        # first real run exited here before ever polling, because
        # remaining==0 while pending==1 - a bug in this condition, not in
        # the API).
        if current_run["status"] == "completed":
            print(f"run completed: counters={current_run['counters']}")
            break

        status, envelope = client.next_decision_request(wait=poll_wait)
        if status == 204 or envelope is None:
            continue  # no request yet - loop again, this is normal per the 25s receive wait

        authorization_id = envelope["authorization_id"]
        delivery_count = envelope.get("delivery_count", 1)
        event_data = envelope["data"]

        if authorization_id in _already_decided:
            print(f"REDELIVERY DETECTED: {authorization_id} (delivery_count={delivery_count}) - already decided, skipping resubmission")
            _redeliveries.append(authorization_id)
            continue

        deadline_at = event_data.get("deadline_at")
        source_authorization_id = event_data["authorization"].get("source_authorization_id")
        t0 = time.monotonic()

        # Use the embedded run-start mandate snapshot, not a fresh GET, per
        # the documented "existing run keeps its original snapshot" behavior.
        mandate_snapshot = event_data["mandate"]
        policy = mandate_snapshot_to_engine_policy(mandate_snapshot)
        purchase = authorization_event_to_purchase(event_data)

        result = evaluate_purchase(policy, purchase)
        decision, reason_codes, customer_message, evidence = engine_decision_to_leash_decision(result)

        engine_elapsed_ms = (time.monotonic() - t0) * 1000
        print(f"authorization_id={authorization_id} source={source_authorization_id} "
              f"decision={decision} deadline_at={deadline_at} engine_elapsed_ms={engine_elapsed_ms:.2f}")

        try:
            response = client.submit_decision(
                authorization_id, decision, reason_codes, customer_message, evidence,
                source_authorization_id=source_authorization_id,
            )
        except LeashApiError as error:
            print(f"DECISION SUBMISSION FAILED: status={error.status} error={error.error_body}")
            raise

        submission_elapsed_ms = (time.monotonic() - t0) * 1000
        deadline_remaining_ms = None
        deadline_met = None
        if deadline_at:
            deadline_remaining_ms = (_parse_iso(deadline_at) - datetime.now(timezone.utc)).total_seconds() * 1000
            deadline_met = deadline_remaining_ms >= 0

        _already_decided.add(authorization_id)
        decided.append({
            **response,
            "_decision_latency_ms": submission_elapsed_ms,
            "_deadline_remaining_ms": deadline_remaining_ms,
            "_deadline_met": deadline_met,
        })
        print(f"submitted: status={response['status']} is_final={response['is_final']} idempotent_replay={response.get('idempotent_replay')} "
              f"decision_latency_ms={submission_elapsed_ms:.2f} deadline_remaining_ms={deadline_remaining_ms} deadline_met={deadline_met}")

        if response["is_final"] is False:
            print(f"STEP_UP OPEN (not resolved): {authorization_id} human_deadline_at={response.get('human_deadline_at')} "
                  "- /resolve is out of P0 scope; this authorization is left awaiting_customer, not faked as approve/decline.")

    return {"run_id": run_id, "mandate_id": mandate_id, "decided": decided, "redeliveries": list(_redeliveries)}


if __name__ == "__main__":
    scenario = sys.argv[1] if len(sys.argv) > 1 else "SCEN0000"
    try:
        outcome = run_scenario(scenario)
        print("\n=== RESULT ===")
        for d in outcome["decided"]:
            print(f"{d['source_authorization_id']}: {d['decision']} (is_final={d['is_final']})")
    except LeashApiError as error:
        print(f"\nLEASH API ERROR: status={error.status} body={error.error_body}")
        sys.exit(1)
    except KeyError as error:
        print(f"\nMISSING CONFIG: {error} - set LEASH_BASE_URL and TEAM_API_KEY in backend/.env")
        sys.exit(1)
