"""P0 worker: run ONE scenario against the real Leash production server,
reusing the existing decision_engine.evaluate_purchase() unchanged.

Usage:
    cd backend && source .venv/bin/activate
    python3 leash_worker.py SCEN0000

Requires LEASH_BASE_URL and TEAM_API_KEY in the environment (e.g. via a
gitignored backend/.env, loaded below with python-dotenv). Never prints
either value.
"""
from __future__ import annotations

import sys
import time

from dotenv import load_dotenv

load_dotenv()

from leash_adapter import authorization_event_to_purchase, engine_decision_to_leash_decision, mandate_snapshot_to_engine_policy
from leash_client import LeashApiError, LeashClient
from decision_engine import evaluate_purchase

# A generous, hand-authored mandate for this connection-check run - NOT
# generated by the local LLM parser (that produces our own flat Schema, not
# the real Viseca hard_rules shape). Deliberately permissive so a single
# connection-check purchase is expected to approve.
TEST_MANDATE_INSTRUCTION = "Allow purchases up to CHF 1000 per item."
TEST_MANDATE_HARD_RULES = [
    {"field": "authorization.billing_amount_chf", "operator": "<=", "value": 1000, "currency": "CHF", "scope": "purchase"}
]

# Process-lifetime only, per P0 scope - no durable store yet (same
# no-persistence limitation already true of the local demo flow).
_already_decided: set[str] = set()


def run_scenario(scenario_id: str) -> dict:
    client = LeashClient()

    print("== /healthz ==")
    print(client.healthz())

    print("== /v1/bootstrap ==")
    boot = client.bootstrap()
    decision_timeout = boot["timeouts"]["decision_timeout_seconds"]
    poll_wait = int(boot["timeouts"]["long_poll_max_wait_seconds"])
    print(f"decision_timeout_seconds={decision_timeout} long_poll_max_wait_seconds={poll_wait} pack_version={boot.get('pack_version')}")

    print("== create + confirm mandate ==")
    draft = client.create_mandate(TEST_MANDATE_INSTRUCTION, TEST_MANDATE_HARD_RULES)
    draft_id = draft["draft_id"]
    confirmed = client.confirm_mandate(draft_id)
    mandate_id = confirmed["mandate_id"]
    print(f"mandate_id={mandate_id} status={confirmed['status']}")

    print(f"== create scenario run for {scenario_id} ==")
    run = client.create_scenario_run(mandate_id, scenario_id)
    run_id = run["run_id"]
    print(f"run_id={run_id} status={run['status']} counters={run['counters']}")

    decided = []
    while True:
        current_run = client.get_scenario_run(run_id)
        if current_run["status"] == "completed" or current_run["counters"]["remaining"] == 0:
            print(f"run completed: counters={current_run['counters']}")
            break

        status, envelope = client.next_decision_request(wait=poll_wait)
        if status == 204 or envelope is None:
            continue  # no request yet - loop again, this is normal per the 25s receive wait

        authorization_id = envelope["authorization_id"]
        delivery_count = envelope.get("delivery_count", 1)
        event_data = envelope["data"]

        if authorization_id in _already_decided:
            print(f"redelivery of {authorization_id} (delivery_count={delivery_count}) - already decided, skipping resubmission")
            continue

        deadline_at = event_data.get("deadline_at")
        t0 = time.monotonic()

        # Use the embedded run-start mandate snapshot, not a fresh GET, per
        # the documented "existing run keeps its original snapshot" behavior.
        mandate_snapshot = event_data["mandate"]
        policy = mandate_snapshot_to_engine_policy(mandate_snapshot)
        purchase = authorization_event_to_purchase(event_data)

        result = evaluate_purchase(policy, purchase)
        decision, reason_codes, customer_message, evidence = engine_decision_to_leash_decision(result)

        elapsed_ms = (time.monotonic() - t0) * 1000
        print(f"authorization_id={authorization_id} source={event_data['authorization'].get('source_authorization_id')} "
              f"decision={decision} deadline_at={deadline_at} engine_elapsed_ms={elapsed_ms:.2f}")

        try:
            response = client.submit_decision(authorization_id, decision, reason_codes, customer_message, evidence)
        except LeashApiError as error:
            print(f"DECISION SUBMISSION FAILED: status={error.status} error={error.error_body}")
            raise

        _already_decided.add(authorization_id)
        decided.append(response)
        print(f"submitted: status={response['status']} is_final={response['is_final']} idempotent_replay={response.get('idempotent_replay')}")

    return {"run_id": run_id, "mandate_id": mandate_id, "decided": decided}


if __name__ == "__main__":
    scenario = sys.argv[1] if len(sys.argv) > 1 else "SCEN0000"
    try:
        outcome = run_scenario(scenario)
        print("\n=== RESULT ===")
        for d in outcome["decided"]:
            print(f"{d['source_authorization_id']}: {d['decision']} (is_final={d['is_final']})")
    except LeashApiError as error:
        print(f"\nLEASH API ERROR: status={error.status} body={error.error_body}")
        sys.exit(1)
    except KeyError as error:
        print(f"\nMISSING CONFIG: {error} - set LEASH_BASE_URL and TEAM_API_KEY in backend/.env")
        sys.exit(1)
